#!/usr/bin/env bash
usage="$(basename "$0") [-cfoh] -- build an Rmd file to a reveal.js presentation"

html_name=presentation.html
target=$html_name

revealjs=reveal.js
cache=.cache
figs=figs

open_after=false

function make_slides {
	# rmarkdown to markdown
	Rscript -e "knitr::knit('presentation.Rmd', 'presentation.md')"

	# markdown to html
	pandoc -o $revealjs/index.html \
		-t revealjs --section-divs -V theme="simple" \
		-c static/style.css -H static/font.html \
		presentation.md

	if [ ! -e "$html_name" ] ; then
		ln -s $revealjs/index.html $html_name
	fi
}

while getopts ":cfoh" opt; do
		case "$opt" in
				c)
						rm -rf $cache
						;;
				f)
						rm -rf $figs
						;;
				o)
						open_after=true
						;;
        h)
            echo "$usage"
            exit
            ;;
				\?)
						echo "Invalid option: -$OPTARG" >&2
            echo "$usage" >&2
						;;
		esac
done

make_slides

if [ "$open_after" = true ] ; then
	open "$target"
fi
